# Generated by Django 5.2.4 on 2025-07-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0002_ticket_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('to-do', 'To-do'), ('in-progress', 'In progress'), ('review', 'Review'), ('done', 'Done')], max_length=15),
        ),
    ]
