# Generated by Django 5.2.4 on 2025-07-11 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0005_rename_prio_task_priority_task_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assignees',
            new_name='assignee_id',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='reviewer',
            new_name='reviewer_id',
        ),
    ]
