# Generated by Django 5.2.4 on 2025-07-11 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0006_rename_assignees_task_assignee_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assignee_id',
            new_name='assignee',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='reviewer_id',
            new_name='reviewer',
        ),
    ]
