# Generated by Django 5.2.4 on 2025-07-11 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0007_rename_assignee_id_task_assignee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='ticket',
            new_name='task',
        ),
    ]
