# Generated by Django 5.2.4 on 2025-07-13 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0013_board_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
